# Copyright 2026 SkillTree
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Continuous Integration

env:
  NODE_VERSION: 26
  JAVA_VERSION: 25

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:

  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - uses: actions/setup-node@v6
      with:
        node-version: ${{ env.NODE_VERSION }}

    - uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ env.JAVA_VERSION }}

    - name: Print Versions
      run: |
        mvn --version
        java -version

    - name: Build
      run: mvn --batch-mode install
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: upload result artifacts
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: CI result artifacts
        path: |
          ./backend/target/*.jar
          ./frontend/target/*.jar
